version: "3"
services:
  redis:
    image: "redis:alpine"
    networks:
      - backend
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    logging:
      driver: "none"
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o ./dist/main /app/main.go" -command="./dist/main"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
